### PR TITLE
Add Breez as app_name for Podcast Value payments

### PR DESCRIPTION
**Pull request by AbelLykens**
This is very untested ;). But it will identify Breez as payment sender

### CODE REVIEW

**Comment by kingonly** [comment]
@AbelLykens do you want to take a shot at PR? Should be an easy one...

**Comment by AbelLykens** [comment]
This is a PR right? Or am I misunderstanding you? ;)

**Comment by kingonly** [comment]
Yep, sorry... Read it from slack, though it's an issue.
Thank you 🙏

**Comment by roeierez** [comment]
@AbelLykens sorry as I merged a PR that was implemented the same as this one: https://github.com/breez/breezmobile/pull/520

I should have take yours since you was the first but I only noticed this after the merge.
Many thanks for your effort.

**Comment by AbelLykens** [comment]
That's okay ;)

**Pull request closed without merging**
