### PR TITLE
Translate texts on POS page

### PR DESCRIPTION
**Pull request by ademar111190**
Thanks to @tlindi for the Finnish translations

How it looks like:

|English|Spanish|Finnish|Portuguese|
|---|---|---|---|
|en|es|fi|pt|

P.S. The POS page build method was a little bit dense and big so I break it on several methods and more pages.

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
Has this PR gone through review in private or otherwise? @roeierez @ademar111190

**Comment by kingonly** [comment]
@erdemyerebasmaz we typically merge translations w/o a review, but let's fix it if it caused any regressions

**Comment by erdemyerebasmaz** [comment]
@kingonly I see, but this PR also included somewhat important UI changes, which caused the sale notes not being added to invoice regression as far as we know.
@ademar111190 Please ping me to review UI changes in the future and separate translation & UI changes where you can, thank you.

**Comment by kingonly** [comment]
@erdemyerebasmaz thanks.
@ademar111190 Erdem suggestion makes sense, let's separate pure translations from business logic changes. Translations can be merged automatically, but business logic changes should be reviewed.

**Pull request merged**
