### PR TITLE
Fix regression - Podcast player dropdown menu icon

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Fixes 
- #1184

Update dependencies to latest

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
CI error is related to https://github.com/juliansteenbakker/mobile_scanner/commit/96af70a248ee0c494f32dbe1205de4b24417cf2c#r123821483
Since the changes are already in place & they've released a package, I have a hunch they'll update the Flutter requirement. Downgrading mobile_scanner to 3.3.0.

**Comment by ubbabeck** [comment]
version 6077.1 testflight works and looks good ✅

**Comment by erdemyerebasmaz** [comment]
> version 6077.1 testflight works and looks good ✅

Thanks Ruben, there will be another build where the issue I mentioned is resolved.
Could you run an overall test on QR scanner?

**Comment by ubbabeck** [comment]
> > version 6077.1 testflight works and looks good ✅
> 
> 
> 
> Thanks Ruben, there will be another build where the issue I mentioned is resolved.
> 
> Could you run an overall test on QR scanner using that build?

Yes no problem 🙏

**Pull request merged**
