### PR TITLE
Remember last selected tab on PoS

### PR DESCRIPTION
**Pull request by ademar111190**
Fixes https://github.com/breez/breezmobile/issues/635

How it looks like:

https://user-images.githubusercontent.com/1225438/143877835-073a516b-4e8e-4d8f-8995-551195347628.mp4

### CODE REVIEW

**Comment by kingonly** [comment]
@ademar111190 is the state persisted after existing Breez also (it should)?

**Comment by ademar111190** [comment]
> @ademar111190 is the state persisted after existing Breez also (it should)?

@kingonly it is persisted :)

**Comment by kingonly** [comment]
Perfect 🙏

**Review by roeierez — COMMENTED** [review]
Nice and clean.

**Comment by tlindi** [comment]
nice :)

**Pull request merged**
