### PR TITLE
Fix backup dialog being shown outside the home screen

### PR DESCRIPTION
**Pull request by ademar111190**
Fixes https://github.com/breez/breezmobile/issues/1221

# How to test
- Let the don't prompt checkbox at the backup warning uncheck
- Execute some action that will trigger a backup (change theme is the easiest)
- Navigate to Receive via btc address
- Wait at least 4 seconds
- The backup dialog should not appear
- Once back to the home, you should see the backup dialog

### CODE REVIEW

**Review by ubbabeck — APPROVED** [review]
Tested and reviewed for android. 

Please bump iOS version in info.plist before merging.

**Comment by roeierez** [comment]
@ademar111190 I think we should separate the issues here:
1. Don't show the dialog if user marked "don't show again"
2. The fact that the dialog is shown not in the home screen.

The first one should be solved, the second one IMO not.
I don't see a problem that the backup dialog is shown (if needed to ) as early as we can.

**Comment by ademar111190** [comment]
@roeierez if we want to show as early as possible, https://github.com/breez/breezmobile/issues/1221 is not a bug at all and we can close this PR.

Is item 1 happening to you? I didn't see this happening.
The bug reported happens If the user "disable Don't prompt again -> click on later -> Go to Receive via BTC address" i.e. prompt is enabled to the user

**Comment by roeierez** [comment]
Of course. I was under the impression that the real bug is ignoring the checkmark.
The fact that the backup prompt on top of the address is not a bug. Let's close it.

**Pull request closed without merging**
