### PR TITLE
Move translations to Breez translations repo

### PR DESCRIPTION
**Pull request by ademar111190**
Breez Translations repo https://github.com/breez/Breez-Translations

### CODE REVIEW

**Comment by tlindi** [comment]
That's nice. I have been shamed to be posting more PRs to master than all of you guys on team combined 🙏

**Comment by erdemyerebasmaz** [comment]
@ademar111190 let's address the issues on translation repo and hold off merging this for a couple days or so while we test this.

**Comment by ademar111190** [comment]
> @ademar111190 let's address the issues on translation repo and hold off merging this for a couple days or so while we test this.

Thanks for the finding @erdemyerebasmaz Problem fixed

**Review by roeierez — APPROVED** [review]

**Review by erdemyerebasmaz — APPROVED** [review]

**Comment by ademar111190** [comment]
> New to github, sorry if I'm doing something wrong. Tried to create a pull request, impossible so here I am.
> 
> You don't have Czech nor Slovak translation and I would love to help with it, I'm just not sure how to create one. Should I just copy the app_en.arb file and upload the translate version somewhere or you have an account @transifex?
> 
> Thanks.

Hi, @CS-HODL thank you, it would be amazing to add Czech and Slovak translations.
We did move all our app translations for this repository https://github.com/breez/Breez-Translations
To add a new translation, do the following:

# Option A

- Fork the repo
- Copy the file [app_en.arb](https://github.com/breez/Breez-Translations/blob/main/lib/app_en.arb) into the same directory with the name "app_«lang code».arb" (if you don't know the language code just write the language name and I'll change it to the correct code later)
- Translate the entries, commit push, and open a PR allowing edition by the maintainers
- Add me and/or other breez devs for reviewing

# Option B

Just download that file, do your translations, and send the file to me by telegram or email.

P.S:
- You can translate the "example" sections, but it is not necessary; it is just a reference for helping the translators
- There are some keys such as `{minSats}` or `{error}` that you need to keep the same name; these are keys to be replaced by some dynamic text at run time.
- You don't need to translate everything; feel free to let other contributors translate some entries keeping the original in English.
- Keep the lines in the same order as the English file is; all translations are in the same order, which makes maintenance much easier.

**Comment by CS-HODL** [comment]
Thanks @ademar111190,

Forked the https://github.com/breez/Breez-Translations, currently working on the translations - need about a week to finish at least one of them, not sure yet what "commit push" means, might need to contact you again. 
I have no idea how to add you or anyone else, if you can link to a guide for dummies, it would help a lot. 

Thanks again.

**Comment by CS-HODL** [comment]
Working on the translation, and came across an issue in app_en.arb - I believe there should be "has" instead of "had". 

connect_to_pay_error_link_expired": "This link had expired and is no longer valid for payment.",

**Pull request merged**
