### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by theDavidCoen**

### CODE REVIEW

**Comment by roeierez** [comment]
@theDavidCoen Thank you very much for this!

**Review by roeierez — APPROVED** [review]

**Comment by ademar111190** [comment]
we have PT, ES, FR, and now IT, Latin family is getting bigger and bigger :)

I'm merging it and I'll add the necessary scaffold asap, thank you very much @theDavidCoen 🙏

**Comment by ademar111190** [comment]
Scaffold added here https://github.com/breez/breezmobile/pull/952 the Italian language will be available on the next breeze build 🙏

**Comment by theDavidCoen** [comment]
great!

**Pull request merged**
