### PR TITLE
fix send guid on episode_guid and id on itemID boostagram field

### LINKED ISSUE #1123: episode_guid is sent in the itemID field for boostagrams
This change seems to have accidentally put a bug into the tlv record. Episode guid should be sent on the episode_guid field and itemID on the itemID field. But currently the episode_guid is sent on the itemID field.

_Originally posted by @Alwin-Stockinger in https://github.com/breez/breezmobile/issues/1032#issuecomment-1512863498_

### PR DESCRIPTION
**Pull request by Alwin-Stockinger**
Fixes #1123

The guid should be sent on the episode_guid field and the episode id on the itemID field

### CODE REVIEW

**Comment by kingonly** [comment]
@ademar111190 can you please review?
@Alwin-Stockinger thank you so much 🙏

**Comment by ademar111190** [comment]
I have to test it yet, but at first glance, it seems it will reintroduce this bug https://github.com/breez/breezmobile/pull/1008#issuecomment-1366672359

**Comment by Alwin-Stockinger** [comment]
> I have to test it yet, but at first glance, it seems it will reintroduce this bug [#1008 (comment)](https://github.com/breez/breezmobile/pull/1008#issuecomment-1366672359)

Ah yes this will be a problem, do you pull the podcastindex episode id somewhere? This should be set in the itemID field otherwise it shouldn't be set.
The episode guid should still be set in the episode_guid field.

**Comment by ademar111190** [comment]
Thanks @Alwin-Stockinger I'll check if we are using `itemID` somewhere else, other than that LGTM

**Review by ademar111190 — APPROVED** [review]
I didn't find any potential problems; thank you for the PR!!!

**Pull request merged**
