### PR TITLE
Add secure flag to main activity

### PR DESCRIPTION
**Pull request by ademar111190**
Based on https://github.com/breez/breezmobile/issues/184 suggestion

# Before

https://user-images.githubusercontent.com/1225438/122447037-b1729100-cf79-11eb-993f-f6662fe7300e.mp4

# After

https://user-images.githubusercontent.com/1225438/122447048-b46d8180-cf79-11eb-98eb-f6373817e16c.mp4|

### CODE REVIEW

**Comment by kingonly** [comment]
Another wonderful contribution

**Review by roeierez — APPROVED** [review]

**Comment by kingonly** [comment]
@ademar111190 doesn't work for me... Could you please check the master?

**Comment by ademar111190** [comment]
@kingonly I did a fresh build from the master, and it works for me. May you share details of the device you did the test on?

**Comment by bitcoinuser** [comment]
For me didn't work: Device: Android Xioami redmi note 9s

**Comment by kingonly** [comment]
@ademar111190 I'm on OnePlus 8t, but it doesn't work for other users as well. Did you change something in the build maybe? 
This is our APK: https://github.com/breez/breezmobile/wiki/Can-I-download-Breez-APK%3F

**Comment by ademar111190** [comment]
I just download that apk @kingonly and it is still working for me.

Is the Android version of your device the android 11 @bitcoinuser @kingonly ?

Mine is Android 10 and I just found it: https://stackoverflow.com/questions/67223645/setting-flag-secure-does-not-work-when-added-to-onpause-in-android-11

**Comment by kingonly** [comment]
@ademar111190 thanks for testing 🙏 I'm on Android 11. @bitcoinuser do you have an app that works?

**Comment by ademar111190** [comment]
I just update my device to Android 11 and it is working. So It is something else 🤔

**Comment by kingonly** [comment]
Interesting...

**Comment by ademar111190** [comment]
I'm wondering if it is a lifecycle issue, as I add and remove the flag at onPause/onResume lifecycle moments.
Please, if possible, take a look here https://github.com/breez/breezmobile/pull/506

**Pull request merged**
