### PR TITLE
Going Global

### PR DESCRIPTION
**Pull request by mcroad**
This PR tracks the **on-going** effort to translate Breez. 

Breez has the potential to dominate peer-to-peer payments in developing markets where people are desperate for sound money. This PR addresses that need in two ways: adds an easy-to-contribute internationalization infraestructure, and adds Spanish as the first translation.

Translations are stored as plain JSON files in `assets/locales/{language}.json`. I'm using the [`flutter_i18n`](https://github.com/ilteoood/flutter_i18n) library. `flutter_i18n` is a simple wrapper around `flutter_localizations` and `intl` so I don't have to write all the boilerplate code necessary.

This is a **work in progress**. It is not ready to be merged. It requires more translating and thorough testing. Groundwork and configuration are done. I'll continue going through the app and extracting keys where necessary. 

I am not able to test in IOS. If you are able, please run this fork and let me know if everything works.

PRs to this PR and suggestions welcome.

Related to #430, #441, #209, #217

PS: I have not been able to run the app without commenting out [this line](https://github.com/mcroad/breezmobile/blob/19256afbb3c7080a696d63998a3d557d61f050e0/android/app/build.gradle#L46). Any idea why this is happening?

### CODE REVIEW

**Comment by kingonly** [comment]
That's wonderful! Thanks for this contribution!
We will provide feedback and support this effort ofc.

**Comment by roeierez** [comment]
@mcroad Thanks a lot for this PR!
The use of flutter_i18n indeed seems to make things a lot simpler than using the official flutter localisation directly.
Just to make sure we are going with the right infrastructure (because I never used this wrapper), are you aware of any limitations of this library vs the official way?

**Comment by roeierez** [comment]
> PS: I have not been able to run the app without commenting out [this line](https://github.com/mcroad/breezmobile/blob/19256afbb3c7080a696d63998a3d557d61f050e0/android/app/build.gradle#L46). Any idea why this is happening?
In the build.gradle ( several lines before the line you commented) you can see it loads a file called 'key.properties'.
This file contains the properties needed for building such as storeFile, storePassword, etc..
Once you put such file under the 'android' directory you should be fine.
Here is a sample for such file content:

```
storeFile=/Users/roeierez/.android/breez-debug.keystore
keyAlias=test
keyPassword=123456
storePassword=123456
```

**Comment by mcroad** [comment]
@roeierez If I wanted to also translate the `anytime_podcast_player` where should I submit the pr?  https://github.com/breez/anytime_podcast_player or https://github.com/amugofjava/anytime_podcast_player?

**Comment by kingonly** [comment]
@mcroad you submit a PR to the Breez fork and when accepted, we open a PR to anytime repo.

**Comment by kingonly** [comment]
@mcroad any interest to keep working on this? We're willing to help with a bounty...

**Comment by mcroad** [comment]
Shoutout to @ademar111190 for continuing the effort in my absence.

Closing in favor of @ademar111190's PRs.

**Comment by ademar111190** [comment]
@mcroad it would be really nice if you check the Spanish translations, I'm not a native speaker of Spanish so I'm sure some texts can be improved :)

https://github.com/breez/breezmobile/blob/master/lib/l10n/app_es.arb

**Pull request closed without merging**
