### PR TITLE
Fix bitcoin uppercase coming from camera scanner

### PR DESCRIPTION
**Pull request by ademar111190**
Fixes https://github.com/breez/breezmobile/issues/688

For some reason the camera scanner is sending the address as uppercase, I did add a `.toLowerCase()` to fix it,

Fixed a translation text too, the action should be in present mode "TRANSMITIR" instead of past mode "TRANSMITIDO/TRANSMITIDA".

### CODE REVIEW

**Comment by kingonly** [comment]
Something doesn't make sense. Why does the scanner return upper case? It doesn't do it if I scan an url etc... And even if it's upper case, why is that a problem? Shouldn't we support upper case?

**Comment by kingonly** [comment]
We want to generate upper case QRs for Lightning invoices, not sure why it affects scanning.
I'll let @roeierez chime in on the best course of action.

**Comment by roeierez** [comment]
@ademar111190 I think the 

> I found the reason why it is uppercase, it is here https://github.com/breez/breezmobile/blob/master/lib/widgets/compact_qr_image.dart#L64

This is not the scanner it is the QR we show for lightning and bitcoin addresses right? It doesn't explain why the scanner return uppercase strings.

**Comment by roeierez** [comment]
> For some reason the camera scanner is sending the address as uppercase, I did add a `.toLowerCase()` to fix it,

But this fix is not in the scanner, it is is in the QR image we show.

**Comment by kingonly** [comment]
I don't think the scanner always returns upper case. It doesn't if I scan a URL for example.

**Comment by kingonly** [comment]
Maybe the fix is that we need to support "BITCOIN:xxx" strings there.

**Comment by ademar111190** [comment]
> @ademar111190 I think the
> 
> > I found the reason why it is uppercase, it is here https://github.com/breez/breezmobile/blob/master/lib/widgets/compact_qr_image.dart#L64
> 
> This is not the scanner it is the QR we show for lightning and bitcoin addresses right? It doesn't explain why the scanner return uppercase strings.

It is because I got this uppercase following the https://github.com/breez/breezmobile/issues/688

> Maybe the fix is that we need to support "BITCOIN:xxx" strings there.

I think it is better to convert to lowercase because it supports `BITCOIN:` and `bitcoin:` and all possible combinations such as `BiTCoiN:`…

**Comment by kingonly** [comment]
We can convert to lower case, but we need to be careful and review all the cases to make sure it makes sense. Also, we should ensure that the generated QRs remain the same (upper case).

**Comment by roeierez** [comment]
@ademar111190 don't you think the issue is here?: https://github.com/breez/breezmobile/blob/master/lib/services/breezlib/breez_bridge.dart#L667
Schema (bitcoin: prefix) validation should be case sensitive here according to bip21 (https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)

**Comment by ademar111190** [comment]
@roeierez excellent doc that solves all questions, the data is case sensitive and the schema is case insensitive, I'll change the code where you point out because it solves completely 💪

**Comment by ademar111190** [comment]
I did apply the changes, here it is working, thank you 🙏  @roeierez

**Review by roeierez — APPROVED** [review]

**Comment by tlindi** [comment]
Nice, thanks to all team :)

**Pull request merged**
