### PR TITLE
Update Key Name for The Bitcoin Company

### PR DESCRIPTION
**Pull request by Gudnessuche**
Changes made: Updated the key name from 'tbc' to 'TBC' in the configuration for The Bitcoin Company.

### CODE REVIEW

**Comment by kingonly** [comment]
Why is th

**Comment by Gudnessuche** [comment]
It just makes more sense that if 3 words that are all proper nouns, it'd be represented that way.
minor change tbh, but things like tftc for example is usually capitalized as TFTC.

**Comment by Gudnessuche** [comment]
Just going through the json object I also found little corrections like shown in this [PR](https://github.com/breez/breezmobile/pull/1319) as well

**Review by roeierez — APPROVED** [review]
LGTM

**Pull request merged**
