### PR TITLE
Translate custom pos item name

### PR DESCRIPTION
**Pull request by ademar111190**
As we talked on Telegram @kingonly @tlindi

### CODE REVIEW

**Comment by tlindi** [comment]
Does this enable also to select Custom icon?

**Comment by kingonly** [comment]
"It" isn't an icon, it's dynamically derived from the first two letters of the item.

**Comment by tlindi** [comment]
:-( Would it be possible to enable the customization of it too?

eg When PoS uses keypad one could define icon as a cash register or keypad, or what ever is their most commonly sold product.

**Comment by kingonly** [comment]
Not planning to implement something like that. Your feedback is noted and if we'll get similar feedback in the future we'll reconsider, but the cost/value of implementing something like that seems to be high atm.

**Comment by tlindi** [comment]
I see. Works for me.

**Pull request merged**
